config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from config.views import index


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("",index),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

posts/urls.py
from django.urls import path
from posts.views import feeds, comment_add,comment_delete,post_add,tags, post_detail

app_name="posts"
urlpatterns = [
    path("feeds/" , feeds, name="feeds"),
    path("comment_add/", comment_add,name="comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name="comment_delete"),
    path("post_add/",post_add, name="post_add"),
    path("tags/<str:tag_name>/", tags, name="tags"),
    path("<int:post_id>/" , post_detail, name="post_detail"),
]

users/urls.py
from django.urls import path
from users.views import login_view, logout_view, signup

app_name ="users"
urlpatterns = [
    path("login/", login_view,name="login"),
    path("logout/", logout_view,name="logout"),
    path("signup/",signup,name="signup"),
]

templates/_base.html
{% load static %}


<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
       <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>tergram</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% block base_content %}{% endblock %}

</body>
</html>

templates/base.html
{% extends '_base.html' %}

{% block base_content %}
    {% block content %} {% endblock %}

{% endblock %}

templates/base_nav.html
{% extends '_base.html' %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %} {% endblock %}

{% endblock %}

templates/base_slider.html
{% extends '_base.html' %}
{% load static %}

{% block head %}
    <link href="{% static  'splide/splide.css' %}"  rel="stylesheet">
    <script src="{% static 'splide/splide.js' %}"></script>
{% endblock %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %} {% endblock %}
    <script>
        const elms = document.getElementsByClassName('splide');
        for (let i = 0; i < elms.length; i++) {
            new Splide(elms[i]).mount();
        }
    </script>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>termite instagram</title>
</head>
<body>
<h1>tergram</h1>

</body>
</html>

templates/nav.html
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">tergram</a>
    </h1>
    <a href="{% url 'posts:post_add' %}">Add post</a>
    <a href="{%url 'users:logout' %}">Logout</a>
</nav>